project:
  type: book

book:
  # site-url: https://knowledge.freesearchr.org
  site-url: https://freesearchr.github.io/FreesearchR-knowledge/
  title: "FreesearchR knowledge base"
  author: "Andreas Gammelgaard Damsbo"
  date: "8/4/2025"
  chapters:
    - index.qmd
    - qa/qa.qmd
    - part: "FreesearchR app"
      chapters: 
        - app/app.qmd
        - app/data_types.qmd
        - app/visuals.qmd
    - part: "Background"
      chapters: 
        - intro/missingness.qmd
    - part: "Case studies"
      chapters: 
        - cases/case_trial.qmd
        - cases/case_overlapping_measures.qmd
    - part: "Further learning"
      chapters: 
        - further.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand

execute:
  freeze: auto

babelquarto:
  languagelinks: sidebar
  languagecodes:
  - name: da
    text: "Læs på dansk"
  - name: sw
    text: "Soma kwa kiswahili"
  - name: en
    text: "Read in English"
  mainlanguage: 'en'
  languages: ['da', 'sw']
title-da: FreesearchR viden
title-sw: FreesearchR Maarifa
description-da: Introduktion til dataanalyse med FreesearchR
description-sw: Utangulizi wa uchambuzi wa data na FreesearchR
author-da: Andreas Gammelgaard Damsbo
author-sw: Jutta Adelin Jørgensen
lang: en

